version: '3.1'

services:

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kn_springproject_db
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kn_springproject_db
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - mysql
